"""phase1_auth_company

Revision ID: 3579c479178b
Revises: 
Create Date: 2026-07-20 07:44:53.241186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3579c479178b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('default_tone', sa.String(length=50), nullable=False),
    sa.Column('default_call_to_action', sa.String(length=300), nullable=True),
    sa.Column('subscription_status', sa.String(length=40), nullable=False),
    sa.Column('subscription_plan', sa.String(length=40), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_subscription_status'), 'companies', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_companies_trade'), 'companies', ['trade'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('company_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'crew', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'disabled', name='membership_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_user')
    )
    op.create_index(op.f('ix_company_memberships_company_id'), 'company_memberships', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_memberships_user_id'), 'company_memberships', ['user_id'], unique=False)
    op.create_table('company_service_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('metro_area', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_service_areas_city'), 'company_service_areas', ['city'], unique=False)
    op.create_index(op.f('ix_company_service_areas_company_id'), 'company_service_areas', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_service_areas_postal_code'), 'company_service_areas', ['postal_code'], unique=False)
    op.create_index(op.f('ix_company_service_areas_state'), 'company_service_areas', ['state'], unique=False)
    op.create_table('company_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_services_company_id'), 'company_services', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_services_company_id'), table_name='company_services')
    op.drop_table('company_services')
    op.drop_index(op.f('ix_company_service_areas_state'), table_name='company_service_areas')
    op.drop_index(op.f('ix_company_service_areas_postal_code'), table_name='company_service_areas')
    op.drop_index(op.f('ix_company_service_areas_company_id'), table_name='company_service_areas')
    op.drop_index(op.f('ix_company_service_areas_city'), table_name='company_service_areas')
    op.drop_table('company_service_areas')
    op.drop_index(op.f('ix_company_memberships_user_id'), table_name='company_memberships')
    op.drop_index(op.f('ix_company_memberships_company_id'), table_name='company_memberships')
    op.drop_table('company_memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_trade'), table_name='companies')
    op.drop_index(op.f('ix_companies_subscription_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
