"""initial schema

Revision ID: ce3e22caa18e
Revises: 
Create Date: 2026-08-30 14:54:16.923688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3e22caa18e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('default_tone', sa.String(length=50), nullable=False),
    sa.Column('default_call_to_action', sa.String(length=300), nullable=True),
    sa.Column('subscription_status', sa.String(length=40), nullable=False),
    sa.Column('subscription_plan', sa.String(length=40), nullable=False),
    sa.Column('billing_customer_id', sa.String(length=200), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('service_area', sa.String(length=300), nullable=True),
    sa.Column('photo_minimums_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('photo_maximums_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('facebook_group_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_subscription_status'), 'companies', ['subscription_status'], unique=False)
    op.create_index(op.f('ix_companies_trade'), 'companies', ['trade'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_company_id'), 'audit_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('company_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'manager', 'crew', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'disabled', name='membership_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_user')
    )
    op.create_index(op.f('ix_company_memberships_company_id'), 'company_memberships', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_memberships_user_id'), 'company_memberships', ['user_id'], unique=False)
    op.create_table('company_service_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('metro_area', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_service_areas_city'), 'company_service_areas', ['city'], unique=False)
    op.create_index(op.f('ix_company_service_areas_company_id'), 'company_service_areas', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_service_areas_postal_code'), 'company_service_areas', ['postal_code'], unique=False)
    op.create_index(op.f('ix_company_service_areas_state'), 'company_service_areas', ['state'], unique=False)
    op.create_table('company_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_services_company_id'), 'company_services', ['company_id'], unique=False)
    op.create_table('contractor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('public_slug', sa.String(length=220), nullable=False),
    sa.Column('headline', sa.String(length=300), nullable=True),
    sa.Column('public_description', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('lead_form_enabled', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=300), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractor_profiles_company_id'), 'contractor_profiles', ['company_id'], unique=True)
    op.create_index(op.f('ix_contractor_profiles_featured'), 'contractor_profiles', ['featured'], unique=False)
    op.create_index(op.f('ix_contractor_profiles_public_slug'), 'contractor_profiles', ['public_slug'], unique=True)
    op.create_index(op.f('ix_contractor_profiles_published'), 'contractor_profiles', ['published'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=True),
    sa.Column('location_display', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('customer_name_private', sa.String(length=200), nullable=True),
    sa.Column('customer_consent_status', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'before_photos_added', 'work_in_progress', 'ready_for_summary', 'ready_to_generate', 'generating', 'awaiting_review', 'revision_requested', 'approved', 'scheduled', 'published', 'publishing', 'publish_issue', 'failed', 'archived', name='job_status'), nullable=False),
    sa.Column('job_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_crew_member', sa.String(length=200), nullable=True),
    sa.Column('featured_before_media_id', sa.UUID(), nullable=True),
    sa.Column('featured_after_media_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('privacy_mode', sa.String(length=40), nullable=False),
    sa.Column('generation_version', sa.Integer(), nullable=False),
    sa.Column('latest_generation_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_city'), 'jobs', ['city'], unique=False)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_by'), 'jobs', ['created_by'], unique=False)
    op.create_index(op.f('ix_jobs_deleted_at'), 'jobs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_jobs_service_key'), 'jobs', ['service_key'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'read', 'failed', name='notification_status'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('publishing_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('external_account_id', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'disconnected', 'error', 'pending', name='publishing_connection_status'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishing_connections_company_id'), 'publishing_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_publishing_connections_platform'), 'publishing_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_publishing_connections_status'), 'publishing_connections', ['status'], unique=False)
    op.create_table('directory_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('contractor_profile_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('public_title', sa.String(length=300), nullable=False),
    sa.Column('public_summary', sa.Text(), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=True),
    sa.Column('location_display', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'unpublished', 'flagged', 'removed', name='directory_listing_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=300), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('structured_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contractor_profile_id'], ['contractor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_listings_city'), 'directory_listings', ['city'], unique=False)
    op.create_index(op.f('ix_directory_listings_company_id'), 'directory_listings', ['company_id'], unique=False)
    op.create_index(op.f('ix_directory_listings_contractor_profile_id'), 'directory_listings', ['contractor_profile_id'], unique=False)
    op.create_index(op.f('ix_directory_listings_featured'), 'directory_listings', ['featured'], unique=False)
    op.create_index(op.f('ix_directory_listings_job_id'), 'directory_listings', ['job_id'], unique=True)
    op.create_index(op.f('ix_directory_listings_service_key'), 'directory_listings', ['service_key'], unique=False)
    op.create_index(op.f('ix_directory_listings_slug'), 'directory_listings', ['slug'], unique=True)
    op.create_index(op.f('ix_directory_listings_state'), 'directory_listings', ['state'], unique=False)
    op.create_index(op.f('ix_directory_listings_status'), 'directory_listings', ['status'], unique=False)
    op.create_table('generation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='generation_run_status'), nullable=False),
    sa.Column('generation_type', sa.Enum('initial', 'regenerate', name='generation_type'), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('length_preference', sa.String(length=40), nullable=True),
    sa.Column('user_instruction', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(length=40), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_runs_job_id'), 'generation_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_runs_status'), 'generation_runs', ['status'], unique=False)
    op.create_table('job_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'kind', 'idempotency_key', name='uq_job_submission_idempotency')
    )
    op.create_index(op.f('ix_job_submissions_company_id'), 'job_submissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_submissions_job_id'), 'job_submissions', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_submissions_kind'), 'job_submissions', ['kind'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.Enum('image', 'audio', 'video', 'document', name='media_asset_type'), nullable=False),
    sa.Column('stage_label', sa.Enum('before', 'progress', 'after', 'unclassified', name='media_stage_label'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('processing_status', sa.Enum('pending_upload', 'uploaded', 'processing', 'ready', 'failed', name='media_processing_status'), nullable=False),
    sa.Column('moderation_status', sa.String(length=40), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_company_id'), 'media_assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_media_assets_job_id'), 'media_assets', ['job_id'], unique=False)
    op.create_index(op.f('ix_media_assets_stage_label'), 'media_assets', ['stage_label'], unique=False)
    op.create_table('content_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('generation_run_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('primary_social', 'short_caption', 'before_after', 'directory_listing', 'educational', name='content_type'), nullable=False),
    sa.Column('platform_target', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body_generated', sa.Text(), nullable=False),
    sa.Column('body_edited', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.String(length=300), nullable=True),
    sa.Column('hashtags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'awaiting_review', 'approved', 'rejected', 'superseded', name='content_variant_status'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_variants_content_type'), 'content_variants', ['content_type'], unique=False)
    op.create_index(op.f('ix_content_variants_generation_run_id'), 'content_variants', ['generation_run_id'], unique=False)
    op.create_index(op.f('ix_content_variants_job_id'), 'content_variants', ['job_id'], unique=False)
    op.create_index(op.f('ix_content_variants_status'), 'content_variants', ['status'], unique=False)
    op.create_table('directory_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contractor_profile_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('source_project_id', sa.UUID(), nullable=True),
    sa.Column('source_page_type', sa.String(length=60), nullable=True),
    sa.Column('source_page_url', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('project_location', sa.String(length=200), nullable=True),
    sa.Column('service_requested', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=40), nullable=True),
    sa.Column('lead_status', sa.Enum('new', 'contacted', 'booked', 'won', 'lost', 'spam', name='directory_lead_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contractor_profile_id'], ['contractor_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_project_id'], ['directory_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_leads_company_id'), 'directory_leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_directory_leads_contractor_profile_id'), 'directory_leads', ['contractor_profile_id'], unique=False)
    op.create_index(op.f('ix_directory_leads_lead_status'), 'directory_leads', ['lead_status'], unique=False)
    op.create_index(op.f('ix_directory_leads_source_project_id'), 'directory_leads', ['source_project_id'], unique=False)
    op.create_table('directory_listing_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('directory_listing_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('stage_label', sa.String(length=40), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['directory_listing_id'], ['directory_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directory_listing_media_directory_listing_id'), 'directory_listing_media', ['directory_listing_id'], unique=False)
    op.create_index(op.f('ix_directory_listing_media_media_asset_id'), 'directory_listing_media', ['media_asset_id'], unique=False)
    op.create_table('job_structured_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('generation_run_id', sa.UUID(), nullable=True),
    sa.Column('customer_problem', sa.Text(), nullable=True),
    sa.Column('work_completed', sa.Text(), nullable=True),
    sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('duration_text', sa.String(length=100), nullable=True),
    sa.Column('customer_reaction', sa.Text(), nullable=True),
    sa.Column('homeowner_advice', sa.Text(), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('location_context', sa.String(length=200), nullable=True),
    sa.Column('differentiators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generation_run_id'], ['generation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_structured_details_job_id'), 'job_structured_details', ['job_id'], unique=True)
    op.create_table('voice_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('audio_asset_id', sa.UUID(), nullable=True),
    sa.Column('transcript_raw', sa.Text(), nullable=True),
    sa.Column('transcript_edited', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('transcription_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='transcription_status'), nullable=False),
    sa.Column('transcription_provider', sa.String(length=40), nullable=True),
    sa.Column('transcription_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_summaries_job_id'), 'voice_summaries', ['job_id'], unique=True)
    op.create_index(op.f('ix_voice_summaries_transcription_status'), 'voice_summaries', ['transcription_status'], unique=False)
    op.create_table('publication_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('content_variant_id', sa.UUID(), nullable=True),
    sa.Column('destination_type', sa.Enum('social', 'directory', name='publication_destination_type'), nullable=False),
    sa.Column('publishing_connection_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'published', 'failed', 'cancelled', 'scheduled', name='publication_job_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('provider_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_variant_id'], ['content_variants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publishing_connection_id'], ['publishing_connections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_jobs_destination_type'), 'publication_jobs', ['destination_type'], unique=False)
    op.create_index(op.f('ix_publication_jobs_idempotency_key'), 'publication_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_publication_jobs_job_id'), 'publication_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_publishing_connection_id'), 'publication_jobs', ['publishing_connection_id'], unique=False)
    op.create_index(op.f('ix_publication_jobs_status'), 'publication_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_jobs_status'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_publishing_connection_id'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_job_id'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_idempotency_key'), table_name='publication_jobs')
    op.drop_index(op.f('ix_publication_jobs_destination_type'), table_name='publication_jobs')
    op.drop_table('publication_jobs')
    op.drop_index(op.f('ix_voice_summaries_transcription_status'), table_name='voice_summaries')
    op.drop_index(op.f('ix_voice_summaries_job_id'), table_name='voice_summaries')
    op.drop_table('voice_summaries')
    op.drop_index(op.f('ix_job_structured_details_job_id'), table_name='job_structured_details')
    op.drop_table('job_structured_details')
    op.drop_index(op.f('ix_directory_listing_media_media_asset_id'), table_name='directory_listing_media')
    op.drop_index(op.f('ix_directory_listing_media_directory_listing_id'), table_name='directory_listing_media')
    op.drop_table('directory_listing_media')
    op.drop_index(op.f('ix_directory_leads_source_project_id'), table_name='directory_leads')
    op.drop_index(op.f('ix_directory_leads_lead_status'), table_name='directory_leads')
    op.drop_index(op.f('ix_directory_leads_contractor_profile_id'), table_name='directory_leads')
    op.drop_index(op.f('ix_directory_leads_company_id'), table_name='directory_leads')
    op.drop_table('directory_leads')
    op.drop_index(op.f('ix_content_variants_status'), table_name='content_variants')
    op.drop_index(op.f('ix_content_variants_job_id'), table_name='content_variants')
    op.drop_index(op.f('ix_content_variants_generation_run_id'), table_name='content_variants')
    op.drop_index(op.f('ix_content_variants_content_type'), table_name='content_variants')
    op.drop_table('content_variants')
    op.drop_index(op.f('ix_media_assets_stage_label'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_job_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_company_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_job_submissions_kind'), table_name='job_submissions')
    op.drop_index(op.f('ix_job_submissions_job_id'), table_name='job_submissions')
    op.drop_index(op.f('ix_job_submissions_company_id'), table_name='job_submissions')
    op.drop_table('job_submissions')
    op.drop_index(op.f('ix_generation_runs_status'), table_name='generation_runs')
    op.drop_index(op.f('ix_generation_runs_job_id'), table_name='generation_runs')
    op.drop_table('generation_runs')
    op.drop_index(op.f('ix_directory_listings_status'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_state'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_slug'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_service_key'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_job_id'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_featured'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_contractor_profile_id'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_company_id'), table_name='directory_listings')
    op.drop_index(op.f('ix_directory_listings_city'), table_name='directory_listings')
    op.drop_table('directory_listings')
    op.drop_index(op.f('ix_publishing_connections_status'), table_name='publishing_connections')
    op.drop_index(op.f('ix_publishing_connections_platform'), table_name='publishing_connections')
    op.drop_index(op.f('ix_publishing_connections_company_id'), table_name='publishing_connections')
    op.drop_table('publishing_connections')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_service_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_deleted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_by'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_city'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_contractor_profiles_published'), table_name='contractor_profiles')
    op.drop_index(op.f('ix_contractor_profiles_public_slug'), table_name='contractor_profiles')
    op.drop_index(op.f('ix_contractor_profiles_featured'), table_name='contractor_profiles')
    op.drop_index(op.f('ix_contractor_profiles_company_id'), table_name='contractor_profiles')
    op.drop_table('contractor_profiles')
    op.drop_index(op.f('ix_company_services_company_id'), table_name='company_services')
    op.drop_table('company_services')
    op.drop_index(op.f('ix_company_service_areas_state'), table_name='company_service_areas')
    op.drop_index(op.f('ix_company_service_areas_postal_code'), table_name='company_service_areas')
    op.drop_index(op.f('ix_company_service_areas_company_id'), table_name='company_service_areas')
    op.drop_index(op.f('ix_company_service_areas_city'), table_name='company_service_areas')
    op.drop_table('company_service_areas')
    op.drop_index(op.f('ix_company_memberships_user_id'), table_name='company_memberships')
    op.drop_index(op.f('ix_company_memberships_company_id'), table_name='company_memberships')
    op.drop_table('company_memberships')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_company_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_trade'), table_name='companies')
    op.drop_index(op.f('ix_companies_subscription_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
