"""initial_schema

Revision ID: e304f5555716
Revises: 
Create Date: 2026-08-02 21:46:10.538840

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e304f5555716'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=False),
    sa.Column('service_area', sa.String(length=255), nullable=False),
    sa.Column('photo_minimums_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photo_maximums_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notification_settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_provider_event')
    )
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    op.create_table('contractors',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_contractors_company_email')
    )
    op.create_index(op.f('ix_contractors_company_id'), 'contractors', ['company_id'], unique=False)
    op.create_index(op.f('ix_contractors_email'), 'contractors', ['email'], unique=False)
    op.create_table('social_profiles',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'provider', name='uq_social_profile_company_provider')
    )
    op.create_index(op.f('ix_social_profiles_company_id'), 'social_profiles', ['company_id'], unique=False)
    op.create_table('auth_challenges',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('identifier_type', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_challenges_identifier'), 'auth_challenges', ['identifier'], unique=False)
    op.create_table('auth_identities',
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('last_authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_contractor_id'), 'auth_identities', ['contractor_id'], unique=False)
    op.create_table('jobs',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by_contractor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('location_text', sa.String(length=255), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=False),
    sa.Column('assigned_crew_member', sa.String(length=255), nullable=False),
    sa.Column('public_status', sa.String(length=32), nullable=False),
    sa.Column('internal_status', sa.String(length=32), nullable=False),
    sa.Column('submission_version', sa.Integer(), nullable=False),
    sa.Column('cover_object_key', sa.String(length=512), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_contractor_id'], ['contractors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_public_status'), 'jobs', ['public_status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('contractor_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_contractor_id'), 'refresh_tokens', ['contractor_id'], unique=False)
    op.create_table('social_connections',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('social_profile_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('provider_account_name', sa.String(length=255), nullable=True),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'platform', name='uq_social_connection_company_platform')
    )
    op.create_index(op.f('ix_social_connections_company_id'), 'social_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_social_connections_social_profile_id'), 'social_connections', ['social_profile_id'], unique=False)
    op.create_table('job_events',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_company_id'), 'job_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_contractor_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('photo_category', sa.String(length=16), nullable=True),
    sa.Column('original_object_key', sa.String(length=512), nullable=True),
    sa.Column('preview_object_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_object_key', sa.String(length=512), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('upload_status', sa.String(length=32), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_active_voice', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_contractor_id'], ['contractors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_company_id'), 'media_assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_media_assets_job_id'), 'media_assets', ['job_id'], unique=False)
    op.create_table('job_submissions',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('voice_media_asset_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('submitted_by_contractor_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_contractor_id'], ['contractors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voice_media_asset_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'idempotency_key', name='uq_job_submission_idempotency'),
    sa.UniqueConstraint('job_id', 'version', name='uq_job_submission_version')
    )
    op.create_index(op.f('ix_job_submissions_company_id'), 'job_submissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_submissions_job_id'), 'job_submissions', ['job_id'], unique=False)
    op.create_table('content_packages',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('featured_before_media_id', sa.UUID(), nullable=True),
    sa.Column('featured_after_media_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['featured_after_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['featured_before_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['job_submissions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'version', name='uq_content_package_job_version')
    )
    op.create_index(op.f('ix_content_packages_company_id'), 'content_packages', ['company_id'], unique=False)
    op.create_index(op.f('ix_content_packages_job_id'), 'content_packages', ['job_id'], unique=False)
    op.create_table('generated_assets',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.UUID(), nullable=False),
    sa.Column('destination_type', sa.String(length=32), nullable=False),
    sa.Column('destination_account_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('active_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_version_id'], ['generated_asset_versions.id'], name='fk_generated_assets_active_version', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['content_packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'destination_type', name='uq_generated_asset_package_dest')
    )
    op.create_index(op.f('ix_generated_assets_company_id'), 'generated_assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_generated_assets_package_id'), 'generated_assets', ['package_id'], unique=False)
    op.create_table('generated_asset_versions',
    sa.Column('generated_asset_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_media_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preview_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_asset_id'], ['generated_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_asset_id', 'version', name='uq_generated_asset_version_num')
    )
    op.create_index(op.f('ix_generated_asset_versions_generated_asset_id'), 'generated_asset_versions', ['generated_asset_id'], unique=False)
    op.create_table('publication_attempts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('generated_asset_id', sa.UUID(), nullable=False),
    sa.Column('destination_type', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('request_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_asset_id'], ['generated_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_publication_idempotency')
    )
    op.create_index(op.f('ix_publication_attempts_company_id'), 'publication_attempts', ['company_id'], unique=False)
    op.create_index(op.f('ix_publication_attempts_generated_asset_id'), 'publication_attempts', ['generated_asset_id'], unique=False)
    op.create_index(op.f('ix_publication_attempts_job_id'), 'publication_attempts', ['job_id'], unique=False)
    op.create_table('revision_requests',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('generated_asset_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=32), nullable=False),
    sa.Column('instruction_text', sa.Text(), nullable=True),
    sa.Column('instruction_audio_media_id', sa.UUID(), nullable=True),
    sa.Column('selected_media_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcribed_instruction', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_contractor_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_asset_id'], ['generated_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instruction_audio_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_contractor_id'], ['contractors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revision_requests_company_id'), 'revision_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_revision_requests_job_id'), 'revision_requests', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revision_requests_job_id'), table_name='revision_requests')
    op.drop_index(op.f('ix_revision_requests_company_id'), table_name='revision_requests')
    op.drop_table('revision_requests')
    op.drop_index(op.f('ix_publication_attempts_job_id'), table_name='publication_attempts')
    op.drop_index(op.f('ix_publication_attempts_generated_asset_id'), table_name='publication_attempts')
    op.drop_index(op.f('ix_publication_attempts_company_id'), table_name='publication_attempts')
    op.drop_table('publication_attempts')
    op.drop_index(op.f('ix_generated_asset_versions_generated_asset_id'), table_name='generated_asset_versions')
    op.drop_table('generated_asset_versions')
    op.drop_index(op.f('ix_generated_assets_package_id'), table_name='generated_assets')
    op.drop_index(op.f('ix_generated_assets_company_id'), table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index(op.f('ix_content_packages_job_id'), table_name='content_packages')
    op.drop_index(op.f('ix_content_packages_company_id'), table_name='content_packages')
    op.drop_table('content_packages')
    op.drop_index(op.f('ix_job_submissions_job_id'), table_name='job_submissions')
    op.drop_index(op.f('ix_job_submissions_company_id'), table_name='job_submissions')
    op.drop_table('job_submissions')
    op.drop_index(op.f('ix_media_assets_job_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_company_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_company_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_social_connections_social_profile_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_company_id'), table_name='social_connections')
    op.drop_table('social_connections')
    op.drop_index(op.f('ix_refresh_tokens_contractor_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_jobs_public_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_auth_identities_contractor_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_auth_challenges_identifier'), table_name='auth_challenges')
    op.drop_table('auth_challenges')
    op.drop_index(op.f('ix_social_profiles_company_id'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_contractors_email'), table_name='contractors')
    op.drop_index(op.f('ix_contractors_company_id'), table_name='contractors')
    op.drop_table('contractors')
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
